[project]
name = "openframe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pdfplumber>=0.11.7",
    "pypdf2>=3.0.1",
]
